title: Margit Maple
description: Machine Learning to Predict Beach Groundwater Head Elevation
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-cayman
markdown: kramdown
layout: default
